name: sirah_target
channels:
  - cburns1
  - conda-forge
  - anaconda
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - astropy=4.0.1.post1
  - ca-certificates=2020.4.5.1
  - certifi=2020.4.5.1
  - cycler=0.10.0
  - dbus=1.13.6
  - expat=2.2.9
  - fontconfig=2.13.1
  - freetype=2.10.1
  - gettext=0.19.8.1
  - glib=2.64.2
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - icu=64.2
  - jpeg=9c
  - kiwisolver=1.2.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libffi=3.2.1
  - libgfortran-ng
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.10
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - ncurses=6.1
  - nss=3.47
  - numpy=1.18.1
  - openssl=1.1.1f
  - pandas=1.0.3
  - pcre=8.44
  - pip=20.0.2
  - pthread-stubs=0.4
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - python=3.8.2
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2019.3
  - qt=5.12.5
  - readline=8.0
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.30.1
  - tk=8.6.10
  - tornado=6.0.4
  - wheel=0.34.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - attrs==19.3.0
    - backcall==0.1.0
    - beautifulsoup4==4.9.0
    - bleach==3.1.4
    - bs4==0.0.1
    - chardet==3.0.4
    - decorator==4.4.2
    - defusedxml==0.6.0
    - dnspython==1.16.0
    - entrypoints==0.3
    - extinction==0.4.2
    - idna==2.9
    - imageio==2.8.0
    - ipykernel==5.2.1
    - ipython==7.13.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.17.0
    - jinja2==2.11.2
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.3
    - jupyter-console==6.1.0
    - jupyter-core==4.6.3
    - lxml==4.5.0
    - markupsafe==1.1.1
    - mistune==0.8.4
    - mysql-connector-python==8.0.19
    - nbconvert==5.6.1
    - nbformat==5.0.5
    - networkx==2.4
    - notebook==6.0.3
    - pandocfilters==1.4.2
    - parso==0.7.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==7.1.1
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.5
    - protobuf==3.6.1
    - psycopg2-binary==2.8.5
    - ptyprocess==0.6.0
    - pygments==2.6.1
    - pypdf2==1.26.0
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - pyrsistent==0.16.0
    - pywavelets==1.1.1
    - pyzmq==19.0.0
    - qtconsole==4.7.3
    - qtpy==1.9.0
    - requests==2.23.0
    - scikit-image==0.16.2
    - scipy==1.4.1
    - send2trash==1.5.0
    - sfdmap==0.1.1
    - sncosmo==2.1.0
    - soupsieve==2.0
    - terminado==0.8.3
    - testpath==0.4.4
    - traitlets==4.3.3
    - urllib3==1.25.9
    - wcwidth==0.1.9
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1

